### ISSUE TITLE
Load crash if file not found

### ISSUE THREAD

**Issue by MartensCedric** [MartensCedric/GoldenEra#13]
![image](https://cloud.githubusercontent.com/assets/18620025/19840246/3450e1b8-9ec8-11e6-8251-8bc8118f8d5a.png)

**Comment by MartensCedric** [comment]
I wrote LAKES.map so it did LAKES.map.map
but If you put a non existing map it breaks and it also says "Load Successful"

**Comment by MartensCedric** [comment]
@MartianSquirrel

**Comment by MartianSquirrel** [comment]
Fixed.
The save command would assign a  null map, since the LoadMap command in MapUtils does not continue if the file is invalid.

The command only needed to verify if the file exists.
